# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a878bced417ce52efcc6767fae9bc0dc48dddf72847cf3d6b7d865c1e7d2640f95dddc310701442ede8d2557be89feae2a2dcbd3221e95a12e41458ed44b465

test:
  secret_key_base: 90839a19dd38bb924695d35204ee976d2cceae8b4ed4908254116abebe33ff1c5d27fbc90a5ff062bfcfeb96d5619827d332cef2a8997d230401db0c730e2434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
